# Generated by Django 3.0.7 on 2020-06-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_question_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='username',
        ),
    ]
