# Generated by Django 3.0.4 on 2020-06-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_remove_question_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
