# Generated by Django 3.0.4 on 2020-07-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_question_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Question4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
