# Generated by Django 3.0.4 on 2020-07-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_question_question4'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question1',
            field=models.CharField(blank=True, max_length=300000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question2',
            field=models.CharField(blank=True, max_length=300000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question3',
            field=models.CharField(blank=True, max_length=300000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question4',
            field=models.CharField(blank=True, max_length=300000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
