# Generated by Django 3.0.4 on 2020-07-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_auto_20200712_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
    ]
