# Generated by Django 3.0.4 on 2020-07-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_remove_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
