# Generated by Django 3.0.4 on 2020-07-13 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
